# Generated by Django 5.2.8 on 2025-11-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testappvariety",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
