# Generated by Django 5.2.8 on 2025-11-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_testappvariety_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="testappvariety",
            name="price",
            field=models.TextField(default=""),
        ),
    ]
